Added test cases to verify flow control towards target input (new)
reaktivity/nukleus-http.spec pull request #12
Opened 2017-04-06 21:12 UTC by cmebarrow

These are test cases necessary to verify the fix for https://github.com/reaktivity/nukleus-http.java/issues/12

2017-04-06 23:42 UTC, jfallows requested changes

2017-04-06 23:42 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/request.fragmented.with.content.length.target.window.exhausted/server/target.rpt
> +closed
Missing newline

2017-04-07 00:11 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/request.fragmented.with.content.length.target.window.exhausted/server/target.rpt
> +closed
added

2017-04-07 00:19 UTC, cmebarrow commented
@jfallows Please don't merge this yet till I oonto your review comment on the other PR (I may need to alter a test case or add one)

2017-04-08 00:25 UTC, cmebarrow commented
@jfallows Ready for re-review and merge. I reorganized to isolate all tests relating to flow control and fragmentation and improved them a bit.

2017-04-10 23:33 UTC, jfallows approved these changes

2017-04-10 23:51 UTC, merged