Use half duplex in the high-level spec scripts
reaktivity/nukleus-http.spec pull request #33
Opened 2017-07-24 22:42 UTC by cmebarrow

(except where upgrade occurs)
Also added a couple of test cases for abort

2017-07-24 22:55 UTC, jfallows requested changes

2017-07-24 22:55 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.gets.response.with.multiple.content.lengths/server.rpt
> -connected
Removed intentionally?

2017-07-24 22:55 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.should.preserve.unrecognized.headers/server.rpt
> -connected
Removed intentionally?

2017-07-24 22:55 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.should.preserve.unrecognized.headers/client.rpt
> -connected
Removed intentionally?

2017-07-24 22:55 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.or.gateway.must.reject.obs.in.header.value/server.rpt
> -connected
Removed intentionally?

2017-07-24 22:55 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.or.gateway.must.reject.obs.in.header.value/client.rpt
> -connected
Removed intentionally?

2017-07-24 22:55 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.gets.response.with.multiple.content.lengths/client.rpt
> -connected
Removed intentionally?

2017-07-24 22:55 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/transfer.codings/multiple.requests.transfer.encoding.chunked/server.rpt
>  write nukleus:begin.ext ${http:header("status", "200")}
Strictly speaking, shouldn't this happen after reading the chunks?

2017-07-24 22:55 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/transfer.codings/multiple.requests.transfer.encoding.chunked/server.rpt
>  write nukleus:begin.ext ${http:header("status", "200")}
Note: also applies to other similar tests.

2017-07-24 22:55 UTC, jfallows commented on src/test/java/org/reaktivity/specification/http/rfc7230/ConnectionManagementIT.java
> +    public void requestAndAbortBeforeResponseHeadersComplete() throws Exception
Please make sure all IT test names have test names starting with `shouldXXX`.

2017-07-25 00:25 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.gets.response.with.multiple.content.lengths/server.rpt
> -connected
no, fixed

2017-07-25 00:25 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.should.preserve.unrecognized.headers/server.rpt
> -connected
no, fixed

2017-07-25 00:26 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.should.preserve.unrecognized.headers/client.rpt
> -connected
no, fixed

2017-07-25 00:26 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.or.gateway.must.reject.obs.in.header.value/server.rpt
> -connected
no, fixed

2017-07-25 00:26 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.or.gateway.must.reject.obs.in.header.value/client.rpt
> -connected
no fixed

2017-07-25 00:27 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/message.format/proxy.gets.response.with.multiple.content.lengths/client.rpt
> -connected
no, fixed

2017-07-25 00:32 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/http/streams/rfc7230/transfer.codings/multiple.requests.transfer.encoding.chunked/server.rpt
>  write nukleus:begin.ext ${http:header("status", "200")}
done

2017-07-25 00:51 UTC, cmebarrow commented on src/test/java/org/reaktivity/specification/http/rfc7230/ConnectionManagementIT.java
> +    public void requestAndAbortBeforeResponseHeadersComplete() throws Exception
Some method names like clientAndServerMustCloseConnectionAfterRequestWithConnectionClose or serverMustCloseConnectionAfterResponseWithConnectionClose make use of the word "must" to indicate the nature of the requirement in the HTTP specification. Are you okay with names like "mustXxx" in addition to "shouldXxx"? Alternative is to lose the "must" information if you think it is unimportant. Also, what do you suggest for names like serverMustCloseConnectionAfterResponseWithConnectionClose? "shouldCloseConnectionAfterResponseWithConnectionClose" loses some meaning. "shouldCloseConnectionAfterResponseWithConnectionCloseWhenActingAsServer" as little bit clumsy but I could live with it. Can you?

2017-07-25 04:17 UTC, jfallows approved these changes

2017-07-25 04:17 UTC, merged